import argparse
import os
import sys
from datetime import datetime

def args_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument('--dataset', type=str, default='cifar100', choices=['cifar100', 'cifar10', 'svhn'], help='name of dataset')
    parser.add_argument('--data_root', type=str, default='dataset', help='dataset root directory for CIFAR/SVHN style datasets')
    parser.add_argument('--train_per_class', type=int, default=500, help='training pool size per class (global across all clients); <=0 means use all')
    parser.add_argument('--base_distribution_pkl', type=str, default='./outputs/data_distribution/task_base_class_10_10client_10class_distribution_1229.pkl', help='optional base-class split pkl path; if provided and exists, fl_main will reuse it instead of regenerating the base split')
    parser.add_argument('--base_model_path', type=str, default='', help='optional pretrained base global model checkpoint path used before incremental training')
    parser.add_argument('--base_model_output_path', type=str, default='', help='optional output checkpoint path for base_model.py base-class pretraining')
    parser.add_argument('--method', type=str, default='FedHCA', help='name of method', choices=['FedHCA', 'FedAvg', 'FedProx', 'FedProx_PODNet', 'FedAvg_PODNet', 'FedProx_iCaRL', 'FedAvg_iCaRL', 'FedProx_EWC', 'FedAvg_EWC'])
    parser.add_argument('--iid_level', type=int, default=6, help='number of data classes for local clients')
    parser.add_argument('--baseclass', type=int, default=10, help='number of classes in the base task')
    parser.add_argument('--learnedclasses', type=int, default=10, help='number of classes already learned before current incremental task')
    parser.add_argument('--img_size', type=int, default=32, help='size of images')
    parser.add_argument('--backbone', type=str, default='resnet18', choices=['resnet18', 'resnet18_cbam', 'mobilenetv2', 'vit_tiny'], help='feature backbone for supplementary robustness runs; default preserves the original ResNet-based setup')
    parser.add_argument('--device', type=int, default=0, help='GPU ID, -1 for CPU')
    parser.add_argument('--batch_size', type=int, default=32, help='size of mini-batch')
    parser.add_argument('--task_size', type=int, default=1, help='number of data classes each task')
    parser.add_argument('--incre_tasks', type=int, default=10, help='number of incremental tasks/classes (assumes 1 class per task in current FedHCA pipeline)')
    parser.add_argument('--seed', type=int, default=2021, help='random seed')
    parser.add_argument('--memory_size', type=int, default=2000, help='size of exemplar memory')
    parser.add_argument('--exemplar_per_class', type=int, default=20, help='max number of exemplars stored per class for rehearsal (FedHCA/GLFC).')
    parser.add_argument('--epochs_local', type=int, default=20, help='local epochs of each global round')
    parser.add_argument('--rounds_global', type=int, default=200, help='total number of global rounds')
    parser.add_argument('--task_global_round', type=int, default=10, help='number of global rounds each task')
    parser.add_argument('--learning_rate', type=float, default=0.1, help='learning rate')
    parser.add_argument('--num_clients', type=int, default=10, help='total number of clients')
    parser.add_argument('--alpha', type=float, default=0.5, help='Dirichlet distribution parameter')
    parser.add_argument('--new_client_num', type=int, default=4, help='number of clients exposed to the new class per task')
    parser.add_argument('--exposure_rounds', type=str, default='0,3,5,5,9,9,9,9,9,9', help='comma-separated exposure rounds for logical clients; default asynchronous exposure pattern')
    parser.add_argument('--incre_sample_splits', type=str, default='3,9,24,64', help='legacy CIFAR incremental sample schedule; used by the CIFAR-style incremental exposure schedule')
    parser.add_argument('--balance_sampler', type=int, default=1, help='use class-balanced sampler for local training (1/0)')
    parser.add_argument('--new_class_boost', type=float, default=2.0, help='extra sampling boost factor for the current task new class (only during exposed training)')
    parser.add_argument('--fedhca_sampler_early_rounds', type=int, default=-1, help='FedHCA-only: control when WeightedRandomSampler is used. -1 keeps legacy behavior; 0 disables sampler; N>0 enables sampler only during the first N exposure rounds.')
    parser.add_argument('--server_ema', type=float, default=0.0, help='EMA factor for server global update: 0 disables; 0.3~0.7 often stabilizes old classes')
    parser.add_argument('--server_ema_fc_new', type=float, default=0.0, help='EMA factor for the current new-class fc row (usually 0 to keep new class fast)')
    parser.add_argument('--fedhca_freeze_backbone', type=str, default='none', choices=['none', 'exposure', 'task'], help='FedHCA-only: freeze backbone and train head only; none=disable, exposure=only expo..expo+3, task=expo..end-of-task')
    parser.add_argument('--fedhca_new_loss_weight', type=float, default=1.0, help='FedHCA-only: extra multiplier on new-class CE during exposed training (>=1).')
    parser.add_argument('--fedhca_protect_new_head', type=int, default=1, help='FedHCA-only: when a batch has no new-class samples, exclude the current new class from CE softmax (1/0).')
    parser.add_argument('--fedhca_protect_recent_old_head', type=int, default=1, help='FedHCA-only: when a batch has no recent-old samples, mask that class logit in CE (1/0).')
    parser.add_argument('--fedhca_recent_old_weight', type=float, default=0.0, help='FedHCA-only: extra additive weight on CE for recent-old class (class_id-1) when present; 0 disables.')
    parser.add_argument('--fedhca_backbone_policy', type=str, default='legacy', choices=['legacy', 'exp_unfreeze_then_freeze', 'exp_lowlr_then_freeze', 'all_freeze'], help='FedHCA-only: backbone update schedule under asynchronous exposure. legacy: use --fedhca_freeze_backbone behavior. exp_unfreeze_then_freeze: exposed clients train backbone only during 4-round exposure window; freeze after; non-exposed always freeze. exp_lowlr_then_freeze: like exp_unfreeze_then_freeze but backbone uses a much smaller LR than head during exposure. all_freeze: freeze backbone for all clients in all rounds.')
    parser.add_argument('--fedhca_freeze_bn', type=int, default=1, help='FedHCA-only BN freeze policy: 0 never; 1 only when freeze_backbone=True; 2 non-exposed rounds and freeze_backbone rounds; 3 always.')
    parser.add_argument('--fedhca_rowbank_final_restore', type=int, default=0, help='FedHCA-only: restore the best historical fc row for each incremental class once at the very end (1/0).')
    parser.add_argument('--fedhca_taskwise_restore', type=int, default=0, help='FedHCA-only: at each task boundary, restore degraded old-class fc rows by blending with their historical best rows (1/0).')
    parser.add_argument('--fedhca_taskwise_restore_ratio', type=float, default=0.7, help='FedHCA-only: restoration trigger if acc_k < ratio * best_acc_k.')
    parser.add_argument('--fedhca_taskwise_restore_threshold', type=float, default=20.0, help='FedHCA-only: restoration trigger if acc_k < threshold (percent).')
    parser.add_argument('--fedhca_taskwise_restore_beta_min', type=float, default=0.3, help='FedHCA-only: minimum restoration strength beta.')
    parser.add_argument('--fedhca_taskwise_restore_beta_max', type=float, default=0.7, help='FedHCA-only: maximum restoration strength beta.')
    parser.add_argument('--fedhca_backbone_lowlr_scale', type=float, default=0.05, help='FedHCA-only: when fedhca_backbone_policy=exp_lowlr_then_freeze, backbone_lr = head_lr * scale.')
    parser.add_argument('--fedhca_protect_past_new_rows', type=int, default=1, help='FedHCA-only: protect all previously-introduced incremental classes with weighted row overwrite from supporting clients (1/0).')
    parser.add_argument('--fedhca_protect_past_new_beta', type=float, default=0.3, help='FedHCA-only: EMA mixing factor for past-new fc row protection.')
    parser.add_argument('--fedhca_protect_past_new_min_support', type=int, default=2, help='FedHCA-only: minimum number of supporting clients required to protect a past-new class row.')
    parser.add_argument('--fedhca_protect_past_new_min_samples', type=int, default=0, help='FedHCA-only: minimum per-client sample count for a class to be considered as supporting that class.')
    parser.add_argument('--fedhca_freeze_past_new_rows_grad', type=int, default=0, help='FedHCA-only: during exposed training, zero gradients of fc rows for all past incremental classes (1/0).')
    parser.add_argument('--fedhca_weight_align_new_row', type=int, default=0, help='FedHCA-only: head calibration after server aggregation. 0 disables; 1 aligns only new row; 2 aligns all incremental rows.')
    parser.add_argument('--fedhca_new_row_bias_scale', type=float, default=1.0, help='FedHCA-only: multiplicative scale applied to fc.bias[new_class_id] after aggregation. 1.0 disables.')
    parser.add_argument('--ablate_server_fedavg', type=int, default=0, help='Ablation: when method=FedHCA, force server aggregation to use FedAvg(w_local) instead of FedHCA cluster_and_aggregate (1/0).')
    parser.add_argument('--ablate_local_plain_train', type=int, default=0, help='Ablation: when method=FedHCA, disable FedHCA local tweaks and use plain local training (train_compare) on each client (1/0).')
    parser.add_argument('--server_ablation', type=str, default='full', choices=['full', 'w/o_clustering', 'w/o_prototype_similarity', 'w/o_update_similarity', 'w/o_contribution_weighting'], help='FedHCA-only server-side ablation switch; full keeps the default behavior.')
    parser.add_argument('--exposure_mode', type=str, default='exponential', choices=['exponential', 'linear', 'random_cumulative'], help='CIFAR-100 exposure schedule mode for supplementary sensitivity experiments.')
    parser.add_argument('--async_timing_mode', type=str, default='fixed_default', choices=['fixed_default', 'fixed_staggered', 'random_timing'], help='CIFAR-100 asynchronous first-exposure timing pattern mode for robustness experiments.')
    parser.add_argument('--proto_noise_sigma', type=float, default=0.0, help='FedHCA-only Gaussian noise sigma applied to uploaded prototypes before server clustering/aggregation.')
    parser.add_argument('--profile_overhead', type=int, default=0, help='Enable communication/computation overhead profiling for CIFAR-100 FedHCA/FedAvg supplementary analysis (1/0).')
    parser.add_argument('--run_tag', type=str, default='', help='Optional run identifier used by standardized result/log filenames; defaults to --date when empty.')
    parser.add_argument('--output_root', type=str, default='./outputs/results', help='Root directory for standardized summary/per-round outputs.')
    parser.add_argument('--log_root', type=str, default='./outputs/logs', help='Root directory for standardized nohup log filenames.')
    parser.add_argument('--auc_window', type=int, default=4, help='Number of consecutive global rounds used when computing AUC_new.')
    parser.add_argument('--date', type=str, default=os.environ.get('EXP_DATE', datetime.now().strftime('%y%m%d')), help='date tag used in output filenames (e.g., 260128)')
    parser.add_argument('--init_classes_learned', type=int, default=80, help='initial number of learned classes')
    args = parser.parse_args()
    args.cli_flags = sorted((d for d in sys.argv[1:] if str(d).startswith('--')))
    return args
